import { KreStat } from './models/kre-stat.model'

export const kreStatList: KreStat[] = [
  {
    name: 'payouts-kin',
    button: 'Payouts (Kin)',
    title: 'Payouts (Kin)',
    yAxisLabel: 'KIN Rewarded',
    xAxisLabel: 'Week Ending',
    table: 'payouts',
    dataLabelName: 'date',
    dataSetName: 'digital_service_name',
    dataSetValue: 'payout_kin',
    displayLegend: true,
    description: [
      `<p>The payouts are calculated proportionally based on <i>Capped Active User Balances</i> for each app with at least one Active User.</p>`,
      `<p>An Active User (for payment calculations) is a unique user-owned wallet with at least 3 spends in the last 30 days.</p>`,
      `<p>Payout data is updated once a week on Wednesdays</p>`,
    ].join(''),
  },
  {
    name: 'payouts-usd',
    button: 'Payouts (USD)',
    title: 'Payouts (USD)',
    yAxisLabel: 'KIN Rewarded (USD)',
    xAxisLabel: 'Week Ending',
    table: 'payouts',
    dataLabelName: 'date',
    dataSetName: 'digital_service_name',
    dataSetValue: 'payout_usd',
    displayLegend: true,
    description: `<p>This is the conversion to USD of KIN payed out to apps using the daily price from CoinGecko</p>`,
  },
  {
    name: 'payouts-daily-kin',
    button: 'Payouts Daily (Kin)',
    title: 'Payouts Daily (Kin)',
    yAxisLabel: 'KIN Rewarded',
    xAxisLabel: 'Date',
    table: 'payouts_daily',
    dataLabelName: 'date',
    dataSetName: 'digital_service_name',
    dataSetValue: 'payout_kin',
    displayLegend: true,
    description: [
      `<p>The payouts are calculated proportionally based on <i>Capped Active User Balances</i> for each app with at least one Active User.</p>`,
      `<p>An Active User (for payment calculations) is a unique user-owned wallet with at least 3 spends in the last 30 days.</p>`,
      `<p>Payout data is updated once a week on Wednesdays</p>`,
    ].join(''),
  },
  {
    name: 'AUB',
    button: 'AUB',
    title: 'Active User Balance',
    yAxisLabel: 'AUB',
    xAxisLabel: 'Date',
    table: 'AUB',
    dataLabelName: 'date',
    dataSetName: 'digital_service_name',
    dataSetValue: 'AUB',
    displayLegend: true,
    description: `<p>Active User Balances are the summed balances of all Active Users in an app at the end of a given day</p>`,
  },
  {
    name: 'AUB-capped',
    button: 'AUB (Capped)',
    title: 'Active User Balance (Capped)',
    yAxisLabel: 'AUB',
    xAxisLabel: 'Date',
    table: 'AUB',
    dataLabelName: 'date',
    dataSetName: 'digital_service_name',
    dataSetValue: 'capped_AUB',
    displayLegend: true,
    description: `<p>Capped Active User Balances is the lesser of the Active User Balance of the app and 100,000*(the number of Active Users in an app)</p>`,
  },
  {
    name: 'MAS',
    button: 'MAS',
    title: 'Monthly Active Spenders',
    yAxisLabel: 'MAS',
    xAxisLabel: 'Date',
    table: 'MAS',
    dataLabelName: 'date',
    dataSetName: 'digital_service_name',
    dataSetValue: 'MAS',
    displayLegend: true,
    description: `<p>MAS is the number of users with at least one spend in a month</p>`,
  },
  {
    name: 'MAE',
    button: 'MAE',
    title: 'Monthly Active Earners',
    yAxisLabel: 'MAE',
    xAxisLabel: 'Date',
    table: 'MAE',
    dataLabelName: 'date',
    dataSetName: 'digital_service_name',
    dataSetValue: 'MAE',
    displayLegend: true,
    description: `<p>MAE is the number of users with at least one earn in a month</p>`,
  },
  {
    name: 'MAU',
    button: 'MAU',
    title: 'Monthly Active Users (>= 1 tx)',
    yAxisLabel: 'MAU',
    xAxisLabel: 'Date',
    table: 'MAU',
    dataLabelName: 'date',
    dataSetName: 'digital_service_name',
    dataSetValue: 'MAU',
    displayLegend: true,
    description: `<p>MAU is the number of users with at least one transaction in a month.</p>`,
  },
  {
    name: 'DAS',
    button: 'DAS',
    title: 'Daily Active Spenders',
    yAxisLabel: 'DAS',
    xAxisLabel: 'Date',
    table: 'DAS',
    dataLabelName: 'date',
    dataSetName: 'digital_service_name',
    dataSetValue: 'DAS',
    displayLegend: true,
    description: `<p>DAS is the number of users with at least one spend in a day</p>`,
  },
  {
    name: 'DAE',
    button: 'DAE',
    title: 'Daily Active Earners',
    yAxisLabel: 'DAE',
    xAxisLabel: 'Date',
    table: 'DAE',
    dataLabelName: 'date',
    dataSetName: 'digital_service_name',
    dataSetValue: 'DAE',
    displayLegend: true,
    description: `<p>DAE is the number of users with at least one earn in a day</p>`,
  },
  {
    name: 'DAU',
    button: 'DAU',
    title: 'Daily Active Users (>= 1 tx)',
    yAxisLabel: 'DAU',
    xAxisLabel: 'Date',
    table: 'DAU',
    dataLabelName: 'date',
    dataSetName: 'digital_service_name',
    dataSetValue: 'DAU',
    displayLegend: true,
    description: [
      `<p>DAU is the number of users with at least one transaction in a day.</p>`,
      `<p>This is different from the definition used for payout calculations.</p>`,
      `<p>Note that for DAU, 'Other' includes accounts outside the app ecosystem.</p>`,
    ].join(''),
  },
  {
    name: 'DET',
    button: 'DET',
    title: 'Daily Earn Transactions',
    yAxisLabel: 'DET',
    xAxisLabel: 'Date',
    table: 'DET',
    dataLabelName: 'date',
    dataSetName: 'digital_service_name',
    dataSetValue: 'DET',
    displayLegend: true,
    description: `<p>DET is the number of apps with at least one earn in a day</p>`,
  },
  {
    name: 'DST',
    button: 'DST',
    title: 'Daily Spend Transactions',
    yAxisLabel: 'DST',
    xAxisLabel: 'Date',
    table: 'DST',
    dataLabelName: 'date',
    dataSetName: 'digital_service_name',
    dataSetValue: 'DST',
    displayLegend: true,
    description: `<p>DST is the number of apps with at least one spend in a day</p>`,
  },
  {
    name: 'TDT',
    button: 'TDT',
    title: 'Total Daily Transactions',
    yAxisLabel: 'TDT',
    xAxisLabel: 'Date',
    table: 'TDT',
    dataLabelName: 'date',
    dataSetName: 'digital_service_name',
    dataSetValue: 'TDT',
    displayLegend: false,
    description: `<p>All transactions for Kin on the blockchain. (Account creations, earns, spends, etc)</p>`,
  },
  {
    name: 'MAA',
    button: 'MAA',
    title: 'Monthly Active Apps',
    yAxisLabel: 'MAA',
    xAxisLabel: 'Date',
    table: 'MAA',
    dataLabelName: 'date',
    dataSetName: 'digital_service_name',
    dataSetValue: 'MAA',
    displayLegend: false,
    description: `<p>MAA is the number of apps that have users earning or spending in the last 30 days</p>`,
  },
  {
    name: 'VF',
    button: 'Volatility Factor',
    title: 'Volatility Factor',
    yAxisLabel: 'VF',
    xAxisLabel: 'Date',
    table: 'VF',
    dataLabelName: 'date',
    dataSetName: 'digital_service_name',
    dataSetValue: 'VF',
    displayLegend: false,
    description: [
      `<p>The Volatility factor is the absolute average deviation in the closing price of Kin as listed on CoinGecko`,
      ` over the last 30 days, divided by the average closing price over the same period.</p>`,
    ].join(''),
  },
]
